# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
title: "F1 Simulator Resource Manager Stack"
stackDescription: "F1SIM"
schemaVersion: 1.1.0
version: "20200301"
locale: "en"

variableGroups:
  - title: "Hidden"
    visible: false
    variables:
    - tenancy_ocid
    - region
    - compartment_ocid
    - INSTALL_HOME
    - install_jdk11
    - freeform_tags
    - instance_ad_number
    - instance_count
    - instance_state
    - cloud_agent_plugins
    - source_type
    - boot_volume_backup_policy
    - block_storage_sizes_in_gbs
    - assign_public_ip
    - public_ip
    
  - title: "General Configuration"
    visible: true  
    variables:
    - customer_contacts
    - package_baseurl
    - package_install

  - title: "Compute Instance Provisioning"
    visible: true  
    variables:
    - instance_display_name
    - shape
    - source_ocid
    - instance_flex_ocpus
    - instance_flex_memory_in_gbs
    - ssh_public_keys
    - local_cidr_block

  - title: "Autonomous Database Provisioning"
    visible: true  
    variables:
    - create_database
    - ADB_NAME
    - IS_FREE_TIER
    - autonomous_database_type
    - autonomous_database_cpu_core_count
    - autonomous_database_data_storage_size_in_tbs
    - database_compartment
    - database

  - title: "Database Configuration"
    visible: true  
    variables:
    - ADMIN_PASSWORD
    - APEX_WORKSPACE
    - DB_USER
    - DB_SCHEMA
    - DB_PASSWORD

variables:
  IS_FREE_TIER:
    type: boolean
    title: "ATP Free Tier"
    required: true
    default: true
    visible:
      create_database

  ADB_NAME:
    type: string
    title: "Database Name"
    required: true
    default: "f1simdb"
    visible:
      create_database

  ADMIN_PASSWORD:
    type: password
    title: "ADMIN User Password - leave blank if random password is preferred"
    required: false
    visible: true
    default: "W3lc0m3SIM123!#"

  APEX_WORKSPACE:
    type: string
    title: "APEX Workspace (for F1SIM)"
    required: true
    visible: true
    default: "LIVELAPS"

  DB_SCHEMA:
    type: string
    title: "Database Schema (for F1SIM)"
    required: true
    visible: true
    default: "SIMUSER"

  DB_USER:
    type: string
    title: "Database User (for F1SIM)"
    required: true
    visible: true
    default: "SIMUSER"

  DB_PASSWORD:
    type: password
    title: "Database Password (for Database User) - leave blank if random password is preferred"
    required: false
    visible: true
    default: "W3lc0m3SIM123"

  package_install:
    type: string
    title: "Package Install"
    required: true
    visible: true
    default: "f1-simulator-cloud/f1-simulator-cloud-v5_0_0-1.tar.gz"

  package_baseurl:
    type: string
    title: "Package Repo URL"
    required: true
    visible: true
    default: "https://rooms.opcvr.com/packages/"

  customer_contacts:
    type: string
    title: "Customer Contact"
    required: true
    visible: true
    default: "demo@withoracle.cloud"

  INSTALL_HOME:
    type: string
    required: true
    visible: false
    default: "."

  autonomous_database_cpu_core_count:
    type: integer
    default: 1
    minimum: 1
    maximum: 64
    title: "Autonomous Database OCPU"
    description: ""
    visible:
      and:
        - not:
          - IS_FREE_TIER
        - create_database

  autonomous_database_data_storage_size_in_tbs:
    type: integer
    default: 1
    minimum: 1
    maximum: 10
    title: "Autonomous Database Storage (TB)"
    description: ""
    visible:
      and:
        - not:
          - IS_FREE_TIER
        - create_database

  create_database:
    title: "Create New Database?"
    type: boolean

  database_compartment:
    type: oci:identity:compartment:id
    title: "Autonomous Database Compartment"
    required: false
    visible:
      not:
        - create_database

  database:
    type: oci:database:autonomousdatabase:id
    title: "Use Existing Autonomous Database"
    required: false
    dependsOn:
      compartmentId: ${database_compartment}
    visible:
      not:
        - create_database

  autonomous_database_type:
    type: enum
    title: "Workload Type"
    default: "OLTP"
    # enumerated values
    enum:
      - OLTP
      - DW
      - AJD
    visible:
      create_database

  source_ocid:
    title: "Source Image"
    description: "Tested with Oracle Linux 8.6"
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${compartment_ocid}
#      operatingSystem: "Canonical Ubuntu"
      operatingSystem: "Oracle Linux"      
      operatingSystemVersion: "8"
      shape: ${shape}

  shape:
    title: "Compute Shape"
    description: "Select a shape"
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
    default: "VM.Standard.E4.Flex"
#    default: "VM.Standard.A1.Flex"

  ssh_public_keys:
    title: "Compute SSH Key"
    type: oci:core:ssh:publickey
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"

  public_ip:
    default: "EPHEMERAL"

  instance_display_name:
    title: "Compute Display Name"
    default: "F1Sim Cloud Ingestion"

  instance_flex_memory_in_gbs:
    title: "Compute Memory (GBs)"
    Description: "Select memory required - Min: 6GB, Max: 24GB"
    type: number
    minimum: 8
    maximum: 32
    default: 8

  instance_flex_ocpus:
    title: "Compute OCPUs"
    Description: "Select OCPUs required - Min: 1, Max: 4"
    type: number
    minimum: 1
    maximum: 4
    default: 1

  assign_public_ip:
    default: true

  local_cidr_block:
    title: "Local CIDR Block"
    Description: "Secures network access to the Compute Instance from this local CIDR block."
    default: "0.0.0.0/0"
    type: string

